### ISSUE TITLE
[Home Page] - Video drag & drop not accepting all of the Videos

### ISSUE THREAD

**Issue by HexAbleSec** [brandonhenry/videoshuffle-releases#1]
This section is not accepting all of the selected videos.

<img width="743" height="875" alt="Image" src="https://github.com/user-attachments/assets/f19c2f79-cb97-4fcd-a818-633c9129c7d7" />

While the advance editor accepts all of them, the console states failed to load resource as it is not found, however I can confirm that the file is right there.

<img width="1937" height="1058" alt="Image" src="https://github.com/user-attachments/assets/a9c53980-2b83-4039-99bd-d53465cebbf6" />

**Comment by brandonhenry** [comment]
@ejluciano  i fixed this in latest. can you confirm?

**Comment by HexAbleSec** [comment]
@brandonhenry it is still the same, it looks like a permission issue though

<img width="1431" height="1095" alt="Image" src="https://github.com/user-attachments/assets/05e77b91-f829-4010-af13-e6d7f1ea35dc" />
